//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public System.Guid DoctorId { get; set; }
        public System.Guid Userid { get; set; }
        public string CMP { get; set; }
        public Nullable<int> SpecialityId { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Users Users { get; set; }
    }
}
