//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicHistory()
        {
            this.MedicHistory_Patient = new HashSet<MedicHistory_Patient>();
        }
    
        public System.Guid MedicHistoryId { get; set; }
        public System.Guid RecipeId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> PatiendId { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicHistory_Patient> MedicHistory_Patient { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
