//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Dates = new HashSet<Dates>();
            this.MedicHistory_Patient = new HashSet<MedicHistory_Patient>();
        }
    
        public System.Guid PacienteId { get; set; }
        public System.Guid UserId { get; set; }
        public int BloodType { get; set; }
        public string Policy { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
    
        public virtual BloodType BloodType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dates> Dates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicHistory_Patient> MedicHistory_Patient { get; set; }
        public virtual Users Users { get; set; }
    }
}
