//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_HospitalVSFundamentalsEntities : DbContext
    {
        public BD_HospitalVSFundamentalsEntities()
            : base("name=BD_HospitalVSFundamentalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodType> BloodType { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<MedicHistory> MedicHistory { get; set; }
        public virtual DbSet<MedicHistory_Patient> MedicHistory_Patient { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Recipe_Details> Recipe_Details { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Atention> Type_Atention { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
