//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dates
    {
        public int DateId { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid PatientId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TypeAtentionId { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Type_Atention Type_Atention { get; set; }
    }
}
