//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public System.Guid DoctorId { get; set; }
        public System.Guid Userid { get; set; }
        public string CMP { get; set; }
        public Nullable<int> SpecialityId { get; set; }
    
        public virtual Speciality Speciality { get; set; }
        public virtual Users Users { get; set; }
    }
}
