//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicHistory()
        {
            this.MedicHistory_Patient = new HashSet<MedicHistory_Patient>();
        }
    
        public System.Guid MedicHistoryId { get; set; }
        public Nullable<System.Guid> RecipeId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> PatiendId { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Reason { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<decimal> temperature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicHistory_Patient> MedicHistory_Patient { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
