//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicHistory_Patient
    {
        public int MedicHistory_Patient1 { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> MedicHistoryId { get; set; }
    
        public virtual MedicHistory MedicHistory { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
