//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalVSFundamentals.UI.Forms.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Dates = new HashSet<Dates>();
            this.MedicHistory_Patient = new HashSet<MedicHistory_Patient>();
        }
    
        public System.Guid PacienteId { get; set; }
        public System.Guid UserId { get; set; }
        public int BloodType { get; set; }
        public string Policy { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
    
        public virtual BloodType BloodType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dates> Dates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicHistory_Patient> MedicHistory_Patient { get; set; }
        public virtual Users Users { get; set; }
    }
}
